# Importing dependencies

In [1]:
from keras.preprocessing.text import one_hot

Sentences

In [2]:
sentence=['I am eating bread',
         'The glass of milk',
         'I am eating banana',
         'The cup of tea',
         'She is sleeping',
         'Who is outside',
         'Good work']

In [3]:
sentence 

['I am eating bread',
 'The glass of milk',
 'I am eating banana',
 'The cup of tea',
 'She is sleeping',
 'Who is outside',
 'Good work']

In [4]:
vocab_size=10000

One hot encoding

In [5]:
onehot_encoding=[one_hot(words,vocab_size) for words in sentence]

In [6]:
print(onehot_encoding)

[[8380, 9412, 5181, 8893], [6951, 8938, 6512, 4846], [8380, 9412, 5181, 5240], [6951, 7750, 6512, 4920], [1550, 6185, 5833], [2785, 6185, 4380], [9415, 9988]]


Word Embedding 

In [7]:
import numpy as np

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

pad_sequence ensures that wehn we are passing sentences through the embedding layers they have same no. of words 

In [8]:
sentence_length=8
embedded=pad_sequences(onehot_encoding,padding='pre',maxlen=sentence_length)

In [9]:
print(embedded)

[[   0    0    0    0 8380 9412 5181 8893]
 [   0    0    0    0 6951 8938 6512 4846]
 [   0    0    0    0 8380 9412 5181 5240]
 [   0    0    0    0 6951 7750 6512 4920]
 [   0    0    0    0    0 1550 6185 5833]
 [   0    0    0    0    0 2785 6185 4380]
 [   0    0    0    0    0    0 9415 9988]]


In [10]:
dimensions=10

In [11]:
model=Sequential()
model.add(Embedding(vocab_size,dimensions,input_length=sentence_length))

model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
embedded[0]

array([   0,    0,    0,    0, 8380, 9412, 5181, 8893], dtype=int32)

In [14]:
print(model.predict(embedded)[0])

1/1 [==============================] - 0s 146ms/step
[[ 0.01856729 -0.0358567  -0.03792717 -0.02554786 -0.04478831 -0.02907169
  -0.03964503 -0.02974268  0.01954002 -0.01573572]
 [ 0.01856729 -0.0358567  -0.03792717 -0.02554786 -0.04478831 -0.02907169
  -0.03964503 -0.02974268  0.01954002 -0.01573572]
 [ 0.01856729 -0.0358567  -0.03792717 -0.02554786 -0.04478831 -0.02907169
  -0.03964503 -0.02974268  0.01954002 -0.01573572]
 [ 0.01856729 -0.0358567  -0.03792717 -0.02554786 -0.04478831 -0.02907169
  -0.03964503 -0.02974268  0.01954002 -0.01573572]
 [-0.00465389  0.03155381 -0.03448265 -0.01284056  0.01563616 -0.00280331
  -0.01572    -0.01673794 -0.00601391  0.04519292]
 [-0.02851975 -0.0182908  -0.01719656 -0.02958702 -0.01484353  0.02285263
   0.02271575  0.03050787  0.02421537  0.03271108]
 [-0.0095898   0.04087636  0.02198834 -0.04720144  0.03161499  0.03904719
   0.01907376 -0.04039074 -0.02571344 -0.01905975]
 [ 0.02024077 -0.03292862  0.01303374  0.03858781  0.00740809 -0.0135586